# نام Workflow
name: Create Shorebird Patch

# این workflow چه زمانی اجرا شود؟
on:
  push:
    branches:
      - main # یا master، بستگی به نام branch اصلی شما دارد

# تعریف Job ها
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. کدهای ریپازیتوری را دانلود می‌کند
      - name: Checkout repository
        uses: actions/checkout@v4 # به‌روزرسانی به نسخه جدیدتر

      # ===================== این خط کلیدی و اصلاح شده است =====================
      # ما از نام صحیح سازمان 'shorebirdtech' استفاده می‌کنیم
      - name: Install Shorebird
        uses: shorebirdtech/setup-shorebird@v1
      # ======================================================================

      # 3. یک release اولیه می‌سازد (این بخش برای پچ‌های بعدی لازم است)
      # با افزودن `|| true`، اگر release از قبل وجود داشته باشد، این مرحله با موفقیت رد می‌شود.
      - name: Build initial release (if not exists)
        run: shorebird release android || true
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

      # 4. یک پچ جدید می‌سازد و آن را برای کاربران منتشر می‌کند
      - name: Build and deploy patch
        run: shorebird patch android
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
