name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      # --- بخش جدید برای ایجاد و استفاده از کلید امضا ---
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
        
      - name: Create key.properties file
        run: |
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
      # --------------------------------------------------

      - name: Build and deploy release/patch
        run: |
          # ابتدا یک release می‌سازیم (اگر وجود نداشت، ساخته می‌شود)
          shorebird release android -- --no-shrink || true
          # سپس پچ را می‌سازیم
          shorebird patch android -- --no-shrink
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
